title: Bibi's Burgers
description: 'We grill the best burgers, to your satisfaction.'
social_link: 'https://www.instagram.com/bibis_burgers/'
social_username: bibis_burgers
github_repo: ''
github_username: broccolini
theme_color: ''
remote_theme: internet-de-france/swiss
baseurl: /bibis
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
